### ISSUE TITLE
indexInfos SparkStrategies.scala in shall be "lazy"

### ISSUE THREAD

**Issue by ChenZhongPu** [InitialDLab/Simba#11]
In [SparkStrategies](https://github.com/InitialDLab/Simba/blob/master/engine/sql/core/src/main/scala/org/apache/spark/sql/execution/SparkStrategies.scala) line 330, we should add `lazy` for `indexInfos`. Otherwise, the `indexInfos`will be empty. Correspondingly,  the `predicates` in [IndexedRelationScan.scala](https://github.com/InitialDLab/Simba/blob/master/engine/sql/core/src/main/scala/org/apache/spark/sql/index/IndexedRelationScan.scala#L182) will always be empty. In other words, it will full scan and skip the index.

**Comment by Skyprophet** [comment]
I agree that this is a bug. Please resolve it in your next pull request.

**Comment by Skyprophet** [comment]
Resolved. Refer to #16.
