### ISSUE TITLE
KNN in RTree does not deal with the case when child of RTreeNode is RTreeLeafEntry

### ISSUE THREAD

**Issue by ChenZhongPu** [InitialDLab/Simba#12]
The [def KNN(Point, (Point, MBR) => Double, Int, Boolean)](https://github.com/InitialDLab/Simba/blob/master/engine/sql/core/src/main/scala/org/apache/spark/sql/index/RTree.scala#L168) does not deal with the case when child of `RTreeNode` is `RTreeLeafEntry`.

It is obviously that the child in `RTreeNode` might be `RTreeLeafEntry`, hence we should add enqueue it or just process such entry in place.

A possible fixing solution:
```scala
             m_child.foreach {
               case entry @ RTreeInternalEntry(mbr, node) =>
                 if (isLeaf) pq.enqueue((entry, distFunc(query, mbr)))
                 else pq.enqueue((node, distFunc(query, mbr)))
               case entry @ RTreeLeafEntry(mbr, m_data, size) =>
                  require(mbr.isInstanceOf[MBR])
                  pq.enqueue((entry, distFunc(query, mbr.asInstanceOf[MBR])))
             }
```

**Comment by Skyprophet** [comment]
Actually, I think you should solve it in this way:
```scala
m_child.foreach(entry =>
    if (isLeaf) pq.enqueue((entry, entry.minDist(query)))
    else pq.enqueue((entry.asInstanceOf[RTreeInternalEntry].node, entry.minDist(query)))
)
```
Since `isLeaf` is a proper flag in the `RTreeNode` to check if it is a leaf node or not.

**Comment by Skyprophet** [comment]
Resolved. Refer to PR #16.
