### ISSUE TITLE
CircleRange code generator error

### ISSUE THREAD

**Issue by gfl94** [InitialDLab/Simba#13]
While conducting a  `CircleRange` query even without an index, the query is shown below:
 ```
SELECT x FROM point1 WHERE POINT(point1.x, point1.y) IN CIRCLERANGE(POINT(100, 100), 1.5)"
```

I'll get a code genaration error because `r = 1.5` and it's transferred into a Decimal type inside SparkSQL, and the code generator will give an error [while comparing](https://github.com/InitialDLab/Simba/blob/master/engine/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/codegen/CodeGenerator.scala#L261) a double with a Decimal value in `generate.java` file which is generated from CodeGenerator. And if I change `r = 1` then the error disappear.

You can reproduce this error by conducting a CircleRange with a double value `r`.

I think the error is caused by the CodeGenerator, the Decimal type in Spark has an implicit conversion to double type, but it can not be invoked by a java compiler from `org.codehaus.commons.compiler`,  what's your opinion?

**Comment by Skyprophet** [comment]
I think I got some idea about this bug. Will deal with it recently.

**Comment by Skyprophet** [comment]
resolved.
