### ISSUE TITLE
sqlContext is null in IndexedRelationScan

### ISSUE THREAD

**Issue by ChenZhongPu** [InitialDLab/Simba#25]
In [line 63 - 66](https://github.com/InitialDLab/Simba/blob/develop/engine/sql/core/src/main/scala/org/apache/spark/sql/index/IndexedRelationScan.scala#L63), we use
```scala
private def selectivity_enabled = sqlContext.conf.indexSelectivityEnable
```
to get the value from `conf`. However, `selectivity_enabled` (similar for `s_level_limit`, `s_threshold` and `index_threshold`) will be used in `flatMap`, which runs on worker nodes.

But **The SparkContext (and thus the SQLContext) is only available in the Driver and not serialized to the Workers**, hence we will get null in `flatMap`.

A feasible solution: use `val` rather than `def`:
```scala
private val selectivity_enabled = sqlContext.conf.indexSelectivityEnable
```

**Comment by Skyprophet** [comment]
My fault... Please fix this on `feature-selectivity` branch so that I can merge it back when that PR is ready. Thanks!

**Comment by Skyprophet** [comment]
Fixed.
