### ISSUE TITLE
QuadTree index support

### ISSUE THREAD

**Issue by gfl94** [InitialDLab/Simba#29]
We can use a QuadTree for range query, add the `QuadTree.scala`  into the same package as `RTree.scala`.

**Comment by Skyprophet** [comment]
Please further support `QuadTree` as a full functional index on both local and global index. And make sure it works when queries are coming in.

**Comment by Skyprophet** [comment]
Resolved, pls refer to PR #48.

**Comment by Skyprophet** [comment]
Reopen for global index support of quad-tree.

**Comment by gfl94** [comment]
Resolve in ticket #54 .
