### ISSUE TITLE
Add unit tests for catalyst/spatial

### ISSUE THREAD

**Issue by coffee1121** [InitialDLab/Simba#32]
Add unit tests for classes in Simba/engine/sql/catalyst/src/main/scala/org/apache/spark/sql/spatial/.
As Simba develops quickly, it needs tests to make sure that its classes are correct.

**Comment by Skyprophet** [comment]
Please do fork the repo and create a PR so that I can start reviewing your codes.

**Comment by coffee1121** [comment]
I have finished tests for all classes in Simba/engine/sql/catalyst/src/main/scala/org/apache/spark/sql/spatial/. There are 4 problems. At present, all tests involves these problems fails.

1. Method minDist(Point) in [LineSegment.scala:95](https://github.com/InitialDLab/Simba/blob/master/engine/sql/catalyst/src/main/scala/org/apache/spark/sql/spatial/LineSegment.scala) is wrong. In details, there is a bug in line 100 and line 101.
At line 100, **t** is the projection of the vector (p - start) on  another vector (end - start)
` var t = ((p.coord(0) - start.coord(0)) * (end.coord(0) - start.coord(0)) + (p.coord(1) - start.coord(1)) * (end.coord(1) - start.coord(1))) / len `
However, in the next line, **t** is used as the ratio between the projection and the length of vector (end - start)
`t = Math.max(0, Math.min(1, t))`
A solution is to divide the result in line 100 by len.

2. Method minDist(Circle) in [Polygon.scala:87](https://github.com/InitialDLab/Simba/blob/master/engine/sql/catalyst/src/main/scala/org/apache/spark/sql/spatial/Polygon.scala) is wrong.
This method simply returns the minimum distance of the center minus the radius. However, this result is the distance between the Circle and the Polygon only when the Polygon does not intersect with the Circle. In other classes, the method minDist returns 0.0 if two Shapes intersect with each other. However, in Polygon.minDist(Circle), this check is ignored.
A solution is to do this check first in the method.

3.  As for the Point which lies on the edge of the Polygon, method intersects returns false. This is different with other Shapes. I don't know whether it is designed to be such thing. In the test, I assume that the point on the edge intersects with the Polygon. If  needed, I will change the test.

4. Method Circle.getMBR  shift the center by sqrt(2) * radius to be the bound of the MBR. However, I think it is enough to shift the center by radius. For example, the MBR of the Circle with center (0, 0) and radius 1 is the rectangle amongst (-1, -1) and (1, 1).

**Comment by Skyprophet** [comment]
Nice work, I will launch another ticket to do hot fix on these problems.

**Comment by coffee1121** [comment]
@Skyprophet Unit tests are checked after bugs are fixed. Test for Shape is added. Pull request has been updated.

**Comment by Skyprophet** [comment]
Fixed. Pls refer to PR #37.
