### ISSUE TITLE
Bug In IndexedRelationScan

### ISSUE THREAD

**Issue by gfl94** [InitialDLab/Simba#40]
In [`IndexedRelationScan`](https://github.com/InitialDLab/Simba/blob/develop/engine/sql/core/src/main/scala/org/apache/spark/sql/index/IndexedRelationScan.scala#L155) line 155 and line 187, `.head` function only take the first predicate into consideration, which will cause wrong result for Treap and Treemap index if there are many predicates `union` together.

I'll list other bugs in this ticket, and fix them together in my Refactor ticket #28 .

**Comment by gfl94** [comment]
If a conjunction predicate contains both the `InCircleRange` and `InRange` , the IndexedRelationScan [line 282](https://github.com/InitialDLab/Simba/blob/develop/engine/sql/core/src/main/scala/org/apache/spark/sql/index/IndexedRelationScan.scala#L282) will union the two result together. 

We need to `intersect` the results together.

**Comment by Skyprophet** [comment]
Resolved after rewrite IndexedRelationScan
