### ISSUE TITLE
Bugs in Treap

### ISSUE THREAD

**Issue by coffee1121** [InitialDLab/Simba#44]
I have written unit test for ![Treap](https://github.com/InitialDLab/Simba/blob/master/engine/sql/core/src/main/scala/org/apache/spark/sql/index/Treap.scala), and I found 3 bugs.

Firstly, in ![range method](https://github.com/InitialDLab/Simba/blob/master/engine/sql/core/src/main/scala/org/apache/spark/sql/index/Treap.scala#L145), if the key of the current node is larger than  high, then range(p.left, low, p.key) will return incorrect answer. For example,  we ask range(3, 5) on the node with key=8. Its left child will return range(3, 8), which exceeds the required range. A simple way to solve this problem is calculate range(p.left, low, high) rather than range(p.left, low, p.key). The same problem involves right child in Line 147.

Secondly, in ![rank method](https://github.com/InitialDLab/Simba/blob/master/engine/sql/core/src/main/scala/org/apache/spark/sql/index/Treap.scala#L118), p.left might be null, so there should be a judgement.

Thirdly, in ![apply method](https://github.com/InitialDLab/Simba/blob/master/engine/sql/core/src/main/scala/org/apache/spark/sql/index/Treap.scala#L223), if  data:Array is empty, then the root node will not be constructed.

**Comment by Skyprophet** [comment]
resolved
