### ISSUE TITLE
No cluster ｅｎｖｉｒｏｎｍｅｎｔ,can i install Simba in singlenode?

### ISSUE THREAD

**Issue by pzz2011** [InitialDLab/Simba#46]

**Comment by Skyprophet** [comment]
Of course. Basically, Simba is a full stack extension of Spark SQL, but we didn't hurt the project structure of Spark. Thus, you can set up Simba in exactly the same way as Spark. You can simply follow the direction for building and deploying Spark to set up Simba (the engine folder).

If you encounter errors in scala-style, please disable this plugin in Spark's root `pom.xml` file.

**Comment by pzz2011** [comment]
thanks. 
Ps: hope to see you  to improve the document of this project.(But Professor Li said that it seems that you(or you group) have no time to do it recently:)

**Comment by Skyprophet** [comment]
Thanks for your suggestion... You got the point that our team don't really have enough time to finish the documentations...
Nevertheless, I will close this ticket for now, and resolve this in the future.
