### ISSUE TITLE
Transplant the index part of Simba to standalone branch

### ISSUE THREAD

**Issue by gfl94** [InitialDLab/Simba#67]
Single package should derive from current stable branch, namely commit f8db35a43e78e9ece00e8a576f1f018364d977b0

**Comment by Skyprophet** [comment]
All IndexedRelation and IndexManager has been transplanted to the standalone branch. Please start working on IndexedRelationScan. Please make a plan first and post it on this issue.

**Comment by Skyprophet** [comment]
Done
