### ISSUE TITLE
distanceJoin using DataFrames in standalone version

### ISSUE THREAD

**Issue by katnegermis** [InitialDLab/Simba#78]
Hello,

I was just trying out the new standalone version of Simba.

I got stuck trying to perform a distanceJoin. 

The following is the program that I used

```scala
package edu.utah.cs.simba.examples

import edu.utah.cs.simba.SimbaContext
import edu.utah.cs.simba.index.RTreeType
import edu.utah.cs.simba.spatial.Point
import org.apache.spark.{SparkConf, SparkContext}

object SQL {
  case class Airport(id: Integer, lat: Double, lon: Double)

  def main(args: Array[String]): Unit = {
    val sparkConf = new SparkConf().setAppName("sql_test").setMaster("spark://127.0.0.1:7077")
    val sc = new SparkContext(sparkConf)
    val simbaContext = new SimbaContext(sc)

    import simbaContext.implicits._
    import simbaContext.SimbaImplicits._

    val left = sc.textFile("openflights_airports.csv")
    	.map(_.split(",")).map(p => Airport(p(0).toInt, p(1).toDouble, p(2).toDouble)).toDF

    val right = left.toDF("id2", "lat2", "lon2")

    left.distanceJoin(right,
                      Point(left("lat"), left("lon")),
                      Point(right("lat"), right("lon")),
                      10.0)
    
    sc.stop()
    println("Finished.")
  }
}
```

The problem seem to me to be that Point accepts only an array of doubles, but since I'm performing a distanceJoin, I'd expect it to accept e.g. Column.

Can you spot an error, either in my code or in the new standalone version of Simba?

**Comment by gfl94** [comment]
Hi, 

You need to perform your distance join query in the following way:

```
left.distanceJoin(right,
      Array("lat", "lon"), // left key string array
      Array("lat2", "lon2"), // right key string array
      10.0)
```

The `standalone` version is still under development, many API has not been migrated to our new `DataFrame` API:)

You can refer to the [source file](https://github.com/InitialDLab/Simba/blob/master/src/main/scala/edu/utah/cs/simba/DataFrame.scala#L136) for datailed supported API.

**Comment by Skyprophet** [comment]
The reason I didn't put Column based API to this is that I cannot find a way to get through all of encapsulations in a totally transparent way... I will keep thinking about this and see if I can find a way to solve it.

Dong
On 12/27/2016 08:17:50, Gefei Li <notifications@github.com> wrote:
Hi,
You need to perform your distance join query in the following way:
left.distanceJoin(right, Array("lat", "lon"), // left key string array Array("lat2", "lon2"), // right key string array 10.0)
The standalone version is still under development, many API has not been migrated to our new DataFrame API:)
You can refer to the source file [https://github.com/InitialDLab/Simba/blob/master/src/main/scala/edu/utah/cs/simba/DataFrame.scala#L136] for datailed supported API.

**Comment by katnegermis** [comment]
Thank you both!
