### ISSUE TITLE
Roadmap to spark 2.1 or 2.x [upgrade]

### ISSUE THREAD

**Issue by merlintang** [InitialDLab/Simba#79]
We can propose a roadmap to extend the standlone 1.6.x version to spark 2.x here.

**Comment by Skyprophet** [comment]
Basically, the whole project will consist of these core parts:
1. Spatial Utils: Partitioner, Indexes
2. Logical Plan: Spatial Predicates, Optimizer
3. Physical Plan: SparkPlans, IndexRelations, IndexRelationScan, Join Execution, SparkStrategy
4. Type Injection: ShapeType
5. Context and API Extension: SimbaConf, DataFrame, IndexManager
6. New Features: Coordinate System, Spatial joins (polygon included).

**Comment by merlintang** [comment]
we can 
migrate: 
1. simbacontext=> simbasessionstate
2. simbadataframe => dataset

add 
sparksession => sparkspession (with simbasessionstate)

**Comment by Skyprophet** [comment]
One thing I think we need in the new migration is a better SBT artifact... I am not familiar with the industry standard for maven or sbt artifacts. @merlintang Do you have any idea about that?

**Comment by merlintang** [comment]
Yes, we can follow the pom file, license, readme and example from the spark
base connector. It will be easier for the simba to be updated and
maintained.
https://github.com/hortonworks-spark/shc

btw: I am working on the migration from 1.6 to 2.1 now.

**Comment by Skyprophet** [comment]
Thanks a lot for your contribution! I am more than appreciating it. Let me know if you have problems with the code.

**Comment by merlintang** [comment]
I updated the current 1.6 branch to 2.1 branch, which is based on the spark 2.1. The interface is changed to SparkSession and Dataset. You can review and fix some bugs from here: 
https://github.com/merlintang/Simba/tree/simba-spark-2.1.

Hopefully, the 2.1 branch will be released in the next month. 

@Skyprophet @gfl94 @ricosfeifei

**Comment by merlintang** [comment]
@Skyprophet  can you review the 2.1 branch and update the 1.6 to 2.1 recently?

**Comment by Skyprophet** [comment]
I will try to make some time to do a pass.

**Comment by merlintang** [comment]
great! after that, we need to show a chart to compare the performance with
other systems based on 2.1 standalone.

**Comment by Skyprophet** [comment]
@merlintang Well, I start reading through the new structure and think we may consider a better way to get through all these abstractions and encapsulation scopes. I created a new ticket #82 to keep track of these. Thus, I will end this ticket here.

BTW, I think that putting Simba's code in `org.apache.spark` is a really really bad idea. We should never do something like that.
