### ISSUE TITLE
Kryo Serializer can be enhanced into our system

### ISSUE THREAD

**Issue by gfl94** [InitialDLab/Simba#8]
Currently I skip the [Kryo serialization](https://github.com/InitialDLab/Simba/blob/develop/engine/sql/catalyst/src/main/java/org/apache/spark/sql/catalyst/expressions/KryoShapeSerializer.java) with the default `java.io.ByteArrayStream`, but `ByteArrayStream` is of low efficiency according to [this blog](http://java-performance.info/java-io-bytearrayoutputstream/), we can get better performance if we can use `Kryo` serialzer.

So I tried to integrate `Kryo` serializer to our system, but there is an issue of class registration, we need to register `JTS.geom.Polygon` on `Kyro`, but I have some problem to find all the classes needed to be register. 

TIP: If you want to try to optimize this, uncomment the kryo part in [KryoShapeSerializer.java](https://github.com/InitialDLab/Simba/blob/develop/engine/sql/catalyst/src/main/java/org/apache/spark/sql/catalyst/expressions/KryoShapeSerializer.java), and add the classes to be register in the [static part](https://github.com/InitialDLab/Simba/blob/develop/engine/sql/catalyst/src/main/java/org/apache/spark/sql/catalyst/expressions/KryoShapeSerializer.java#L34-L40), and conduct a SQL query.

**Comment by Skyprophet** [comment]
@gfl94 Could you give me a link to your sample shape file for test?

**Comment by Skyprophet** [comment]
@gfl94 I think I have resolve this problem by write a customized serializer. Please refer to Commit 6db11d1b51caaa8f62d4d3111a6d1d17c603b6c5.
